FilePaths:
  DataFiles: _datafiles/world/storyworlds
Network:
  HttpPort: 80
  TelnetPort:
  - 33333
Server:
  CurrentVersion: 0.9.1
  Motd: Welcome to StoryWorlds - Step into the pages and screens of your favorite
    fictional worlds.
  MudName: StoryWorlds
  NextRoomId: 1213
SpecialRooms:
  StartRoom: 1
